version: "3"
services:
  db:
    container_name: rails_db
    image: postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
  web:
    container_name: rails_web
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - gems-volume:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
volumes:
  postgres-volume:
  gems-volume:
